# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_generation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image_generation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_generation.proto\x12\x10image_generation\"q\n\x11GenerationRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\x0fnegative_prompt\x18\x02 \x01(\t\x12\x1b\n\x13num_inference_steps\x18\x03 \x01(\x05\x12\x16\n\x0eguidance_scale\x18\x04 \x01(\x02\"C\n\x12GenerationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\x0e\n\x06prompt\x18\x03 \x01(\t2n\n\x0eImageGenerator\x12\\\n\rGenerateImage\x12#.image_generation.GenerationRequest\x1a$.image_generation.GenerationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_generation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATIONREQUEST']._serialized_start=44
  _globals['_GENERATIONREQUEST']._serialized_end=157
  _globals['_GENERATIONRESPONSE']._serialized_start=159
  _globals['_GENERATIONRESPONSE']._serialized_end=226
  _globals['_IMAGEGENERATOR']._serialized_start=228
  _globals['_IMAGEGENERATOR']._serialized_end=338
# @@protoc_insertion_point(module_scope)
